export default {
    APP_SELECT_PROCESS: 'app/SELECT_PROCESS',
    APP_RECEIVED_PROCESSES: 'app/RECEIVED_PROCESSES',
    APP_PROCESS_OPENED: 'app/PROCESS_OPENED',
    
    PROCESS_OPENED: 'process/OPENED',
    PROCESS_ERROR: 'process/ERROR'
};
